// import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "@/components/Navbar";
// import { Toaster } from "react-hot-toast";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <head>
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `(function(){try{var theme=localStorage.getItem('theme')||'light';if(theme==='dark'){document.documentElement.classList.add('dark');}}catch(e){}})();`,
//           }}
//         />
//       </head>
//       <body className="min-h-full flex flex-col">
//         <Navbar />
//         <Toaster
//           position="top-right"
//           toastOptions={{
//             style: {
//               background: "linear-gradient(90deg, #6366f1, #8b5cf6)",
//               color: "#fff",
//               borderRadius: "10px",
//             },
//           }}
//         />

//         {children}
//       </body>
//     </html>
//   );
// }

// import Navbar from "@/components/Navbar";
// import { Toaster } from "react-hot-toast";
// import "./globals.css";
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className="min-h-full flex flex-col">
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               (function() {
//                 try {
//                   var theme = localStorage.getItem('theme') || 'light';
//                   if (theme === 'dark') {
//                     document.documentElement.classList.add('dark');
//                   } else {
//                     document.documentElement.classList.remove('dark');
//                   }
//                 } catch(e) {}
//               })();
//             `,
//           }}
//         />
//         <Navbar />
//         <Toaster />
//         {children}
//       </body>
//     </html>
//   );
// }

import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme') || 'light';
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch(e) {}
                // theme-ready class add karo AFTER theme set ho — transition tab fire hogi
                requestAnimationFrame(function() {
                  requestAnimationFrame(function() {
                    document.documentElement.classList.add('theme-ready');
                  });
                });
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
